import { DownloadIcon, ImageIcon, AlertCircleIcon, Loader2Icon, FileTextIcon } from "lucide-react";

import { useLanguage } from "@/lib/i18n/LanguageContext";

import type { GeneratedResult } from "./types";

interface ResultCardProps {
  result: GeneratedResult;
  showWatermark?: boolean;
}

function downloadUrl(url: string, filename: string) {
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.target = "_blank";
  a.click();
}

export function ResultCard({ result, showWatermark = false }: ResultCardProps) {
  const { combination } = result;
  const { t } = useLanguage();

  const hasDownloadable =
    (result.imageUrl || result.textContent) && result.status === "complete";

  return (
    <div className="group relative overflow-hidden rounded-[8px] border bg-card shadow-sm">
      <div className="flex aspect-square items-center justify-center bg-muted">
        {result.imageUrl ? (
          <div className="relative h-full w-full">
            <img
              src={result.imageUrl}
              alt={combination.prompt}
              className="h-full w-full object-cover"
            />
            {showWatermark && (
              <div className="absolute right-2 bottom-2 rounded bg-black/50 px-2 py-0.5 text-[10px] text-white/70 backdrop-blur-sm">
                Generated by BatchlyAI
              </div>
            )}
            {hasDownloadable && (
              <button
                onClick={() => downloadUrl(result.imageUrl!, `batchlyai-${result.id}.png`)}
                className="absolute top-2 right-2 rounded-lg bg-black/50 p-1.5 text-white/80 opacity-0 backdrop-blur-sm transition-opacity group-hover:opacity-100 hover:bg-black/70"
                title="Download"
              >
                <DownloadIcon className="size-4" />
              </button>
            )}
          </div>
        ) : result.textContent ? (
          <div className="relative flex h-full w-full flex-col items-center justify-center p-4">
            <FileTextIcon className="mb-2 size-6 text-muted-foreground/40" />
            <p className="line-clamp-6 text-center text-sm leading-relaxed text-foreground/80">
              {result.textContent}
            </p>
            {hasDownloadable && (
              <button
                onClick={() => {
                  const blob = new Blob([result.textContent!], { type: "text/plain" });
                  const url = URL.createObjectURL(blob);
                  downloadUrl(url, `batchlyai-${result.id}.txt`);
                  URL.revokeObjectURL(url);
                }}
                className="absolute top-2 right-2 rounded-lg bg-black/50 p-1.5 text-white/80 opacity-0 backdrop-blur-sm transition-opacity group-hover:opacity-100 hover:bg-black/70"
                title="Download"
              >
                <DownloadIcon className="size-4" />
              </button>
            )}
          </div>
        ) : result.status === "error" ? (
          <div className="flex flex-col items-center gap-1 text-muted-foreground/40">
            <AlertCircleIcon className="size-8" />
            <span className="text-xs">{t("resultFailed")}</span>
          </div>
        ) : result.status === "generating" ? (
          <Loader2Icon className="size-8 animate-spin text-muted-foreground/40" />
        ) : (
          <ImageIcon className="size-8 text-muted-foreground/30" />
        )}
      </div>
      <p className="line-clamp-2 px-4 pt-4 text-sm leading-[1.29] text-foreground/80">
        {combination.prompt}
      </p>
      <div className="flex flex-wrap gap-x-3 gap-y-0.5 px-4 pt-2 pb-4 text-xs leading-[1.33] text-muted-foreground">
        {Object.entries(combination.variables).map(([key, val]) => (
          <span key={key}>
            {key}: {val}
          </span>
        ))}
      </div>
    </div>
  );
}
