import { ImageIcon, AlertCircleIcon, Loader2Icon } from "lucide-react";

import { useLanguage } from "@/lib/i18n/LanguageContext";

import type { GeneratedResult } from "./types";

interface ResultCardProps {
  result: GeneratedResult;
  showWatermark?: boolean;
}

export function ResultCard({ result, showWatermark = false }: ResultCardProps) {
  const { combination } = result;
  const { t } = useLanguage();

  return (
    <div className="overflow-hidden rounded-[8px] border bg-card shadow-sm">
      <div className="flex aspect-square items-center justify-center bg-muted">
        {result.imageUrl ? (
          <div className="relative h-full w-full">
            <img
              src={result.imageUrl}
              alt={combination.prompt}
              className="h-full w-full object-cover"
            />
            {showWatermark && (
              <div className="absolute bottom-2 right-2 rounded bg-black/50 px-2 py-0.5 text-[10px] text-white/70 backdrop-blur-sm">
                Generated by BatchlyAI
              </div>
            )}
          </div>
        ) : result.status === "error" ? (
          <div className="flex flex-col items-center gap-1 text-muted-foreground/40">
            <AlertCircleIcon className="size-8" />
            <span className="text-xs">{t("resultFailed")}</span>
          </div>
        ) : result.status === "generating" ? (
          <Loader2Icon className="size-8 animate-spin text-muted-foreground/40" />
        ) : (
          <ImageIcon className="size-8 text-muted-foreground/30" />
        )}
      </div>
      <p className="line-clamp-2 px-4 pt-4 text-sm leading-[1.29] text-foreground/80">
        {combination.prompt}
      </p>
      <div className="flex flex-wrap gap-x-3 gap-y-0.5 px-4 pt-2 pb-4 text-xs leading-[1.33] text-muted-foreground">
        {Object.entries(combination.variables).map(([key, val]) => (
          <span key={key}>
            {key}: {val}
          </span>
        ))}
      </div>
    </div>
  );
}
