/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as AboutRouteImport } from './routes/about'
import { Route as GuestRouteRouteImport } from './routes/_guest/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplatesIndexRouteImport } from './routes/templates/index'
import { Route as CnIndexRouteImport } from './routes/cn/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as WorksWorkIdRouteImport } from './routes/works/$workId'
import { Route as ToolsSlugRouteImport } from './routes/tools/$slug'
import { Route as TemplatesSlugRouteImport } from './routes/templates/$slug'
import { Route as RCodeRouteImport } from './routes/r/$code'
import { Route as MyWorksRouteImport } from './routes/my/works'
import { Route as MyPromptsRouteImport } from './routes/my/prompts'
import { Route as MyGenerationsRouteImport } from './routes/my/generations'
import { Route as GShareIdRouteImport } from './routes/g/$shareId'
import { Route as ExamplesSlugRouteImport } from './routes/examples/$slug'
import { Route as CompareAiBatchGeneratorVsSinglePromptToolsRouteImport } from './routes/compare/ai-batch-generator-vs-single-prompt-tools'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as ApiWorksRouteImport } from './routes/api/works'
import { Route as ApiUploadUrlRouteImport } from './routes/api/upload-url'
import { Route as ApiTemplatesRouteImport } from './routes/api/templates'
import { Route as ApiShareRouteImport } from './routes/api/share'
import { Route as ApiPromptsRouteImport } from './routes/api/prompts'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiGrsWebhookRouteImport } from './routes/api/grs-webhook'
import { Route as ApiGenerationsRouteImport } from './routes/api/generations'
import { Route as ApiGenerateStatusRouteImport } from './routes/api/generate-status'
import { Route as ApiGenerateRouteImport } from './routes/api/generate'
import { Route as ApiExpandVarsRouteImport } from './routes/api/expand-vars'
import { Route as GuestSignupRouteImport } from './routes/_guest/signup'
import { Route as GuestResetPasswordRouteImport } from './routes/_guest/reset-password'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as GuestForgotPasswordRouteImport } from './routes/_guest/forgot-password'
import { Route as ApiWorksLikeRouteImport } from './routes/api/works/like'
import { Route as ApiWorksCommentRouteImport } from './routes/api/works/comment'
import { Route as ApiTemplatesSlugRouteImport } from './routes/api/templates/$slug'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as ApiStripePortalRouteImport } from './routes/api/stripe/portal'
import { Route as ApiStripeCheckoutRouteImport } from './routes/api/stripe/checkout'
import { Route as ApiReferralStatsRouteImport } from './routes/api/referral/stats'
import { Route as ApiReferralGenerateCodeRouteImport } from './routes/api/referral/generate-code'
import { Route as ApiGenerationFilesSplatRouteImport } from './routes/api/generation-files/$'
import { Route as ApiFilesSplatRouteImport } from './routes/api/files/$'
import { Route as ApiDiagEmailRouteImport } from './routes/api/diag/email'
import { Route as ApiAuthGoogleOneTapRouteImport } from './routes/api/auth/google-one-tap'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRouteRoute = GuestRouteRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const CnIndexRoute = CnIndexRouteImport.update({
  id: '/cn/',
  path: '/cn/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksWorkIdRoute = WorksWorkIdRouteImport.update({
  id: '/works/$workId',
  path: '/works/$workId',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSlugRoute = ToolsSlugRouteImport.update({
  id: '/tools/$slug',
  path: '/tools/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesSlugRoute = TemplatesSlugRouteImport.update({
  id: '/templates/$slug',
  path: '/templates/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RCodeRoute = RCodeRouteImport.update({
  id: '/r/$code',
  path: '/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const MyWorksRoute = MyWorksRouteImport.update({
  id: '/my/works',
  path: '/my/works',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPromptsRoute = MyPromptsRouteImport.update({
  id: '/my/prompts',
  path: '/my/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const MyGenerationsRoute = MyGenerationsRouteImport.update({
  id: '/my/generations',
  path: '/my/generations',
  getParentRoute: () => rootRouteImport,
} as any)
const GShareIdRoute = GShareIdRouteImport.update({
  id: '/g/$shareId',
  path: '/g/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesSlugRoute = ExamplesSlugRouteImport.update({
  id: '/examples/$slug',
  path: '/examples/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareAiBatchGeneratorVsSinglePromptToolsRoute =
  CompareAiBatchGeneratorVsSinglePromptToolsRouteImport.update({
    id: '/compare/ai-batch-generator-vs-single-prompt-tools',
    path: '/compare/ai-batch-generator-vs-single-prompt-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorksRoute = ApiWorksRouteImport.update({
  id: '/api/works',
  path: '/api/works',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadUrlRoute = ApiUploadUrlRouteImport.update({
  id: '/api/upload-url',
  path: '/api/upload-url',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTemplatesRoute = ApiTemplatesRouteImport.update({
  id: '/api/templates',
  path: '/api/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShareRoute = ApiShareRouteImport.update({
  id: '/api/share',
  path: '/api/share',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPromptsRoute = ApiPromptsRouteImport.update({
  id: '/api/prompts',
  path: '/api/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGrsWebhookRoute = ApiGrsWebhookRouteImport.update({
  id: '/api/grs-webhook',
  path: '/api/grs-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerationsRoute = ApiGenerationsRouteImport.update({
  id: '/api/generations',
  path: '/api/generations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateStatusRoute = ApiGenerateStatusRouteImport.update({
  id: '/api/generate-status',
  path: '/api/generate-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateRoute = ApiGenerateRouteImport.update({
  id: '/api/generate',
  path: '/api/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExpandVarsRoute = ApiExpandVarsRouteImport.update({
  id: '/api/expand-vars',
  path: '/api/expand-vars',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestSignupRoute = GuestSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestResetPasswordRoute = GuestResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestForgotPasswordRoute = GuestForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => GuestRouteRoute,
} as any)
const ApiWorksLikeRoute = ApiWorksLikeRouteImport.update({
  id: '/like',
  path: '/like',
  getParentRoute: () => ApiWorksRoute,
} as any)
const ApiWorksCommentRoute = ApiWorksCommentRouteImport.update({
  id: '/comment',
  path: '/comment',
  getParentRoute: () => ApiWorksRoute,
} as any)
const ApiTemplatesSlugRoute = ApiTemplatesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiTemplatesRoute,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripePortalRoute = ApiStripePortalRouteImport.update({
  id: '/api/stripe/portal',
  path: '/api/stripe/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeCheckoutRoute = ApiStripeCheckoutRouteImport.update({
  id: '/api/stripe/checkout',
  path: '/api/stripe/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferralStatsRoute = ApiReferralStatsRouteImport.update({
  id: '/api/referral/stats',
  path: '/api/referral/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferralGenerateCodeRoute = ApiReferralGenerateCodeRouteImport.update({
  id: '/api/referral/generate-code',
  path: '/api/referral/generate-code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerationFilesSplatRoute = ApiGenerationFilesSplatRouteImport.update({
  id: '/api/generation-files/$',
  path: '/api/generation-files/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesSplatRoute = ApiFilesSplatRouteImport.update({
  id: '/api/files/$',
  path: '/api/files/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiagEmailRoute = ApiDiagEmailRouteImport.update({
  id: '/api/diag/email',
  path: '/api/diag/email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleOneTapRoute = ApiAuthGoogleOneTapRouteImport.update({
  id: '/api/auth/google-one-tap',
  path: '/api/auth/google-one-tap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/discover': typeof DiscoverRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/forgot-password': typeof GuestForgotPasswordRoute
  '/login': typeof GuestLoginRoute
  '/reset-password': typeof GuestResetPasswordRoute
  '/signup': typeof GuestSignupRoute
  '/api/expand-vars': typeof ApiExpandVarsRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/generate-status': typeof ApiGenerateStatusRoute
  '/api/generations': typeof ApiGenerationsRoute
  '/api/grs-webhook': typeof ApiGrsWebhookRoute
  '/api/health': typeof ApiHealthRoute
  '/api/prompts': typeof ApiPromptsRoute
  '/api/share': typeof ApiShareRoute
  '/api/templates': typeof ApiTemplatesRouteWithChildren
  '/api/upload-url': typeof ApiUploadUrlRoute
  '/api/works': typeof ApiWorksRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/compare/ai-batch-generator-vs-single-prompt-tools': typeof CompareAiBatchGeneratorVsSinglePromptToolsRoute
  '/examples/$slug': typeof ExamplesSlugRoute
  '/g/$shareId': typeof GShareIdRoute
  '/my/generations': typeof MyGenerationsRoute
  '/my/prompts': typeof MyPromptsRoute
  '/my/works': typeof MyWorksRoute
  '/r/$code': typeof RCodeRoute
  '/templates/$slug': typeof TemplatesSlugRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/works/$workId': typeof WorksWorkIdRoute
  '/blog/': typeof BlogIndexRoute
  '/cn/': typeof CnIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/google-one-tap': typeof ApiAuthGoogleOneTapRoute
  '/api/diag/email': typeof ApiDiagEmailRoute
  '/api/files/$': typeof ApiFilesSplatRoute
  '/api/generation-files/$': typeof ApiGenerationFilesSplatRoute
  '/api/referral/generate-code': typeof ApiReferralGenerateCodeRoute
  '/api/referral/stats': typeof ApiReferralStatsRoute
  '/api/stripe/checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe/portal': typeof ApiStripePortalRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/templates/$slug': typeof ApiTemplatesSlugRoute
  '/api/works/comment': typeof ApiWorksCommentRoute
  '/api/works/like': typeof ApiWorksLikeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/discover': typeof DiscoverRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/forgot-password': typeof GuestForgotPasswordRoute
  '/login': typeof GuestLoginRoute
  '/reset-password': typeof GuestResetPasswordRoute
  '/signup': typeof GuestSignupRoute
  '/api/expand-vars': typeof ApiExpandVarsRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/generate-status': typeof ApiGenerateStatusRoute
  '/api/generations': typeof ApiGenerationsRoute
  '/api/grs-webhook': typeof ApiGrsWebhookRoute
  '/api/health': typeof ApiHealthRoute
  '/api/prompts': typeof ApiPromptsRoute
  '/api/share': typeof ApiShareRoute
  '/api/templates': typeof ApiTemplatesRouteWithChildren
  '/api/upload-url': typeof ApiUploadUrlRoute
  '/api/works': typeof ApiWorksRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/compare/ai-batch-generator-vs-single-prompt-tools': typeof CompareAiBatchGeneratorVsSinglePromptToolsRoute
  '/examples/$slug': typeof ExamplesSlugRoute
  '/g/$shareId': typeof GShareIdRoute
  '/my/generations': typeof MyGenerationsRoute
  '/my/prompts': typeof MyPromptsRoute
  '/my/works': typeof MyWorksRoute
  '/r/$code': typeof RCodeRoute
  '/templates/$slug': typeof TemplatesSlugRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/works/$workId': typeof WorksWorkIdRoute
  '/blog': typeof BlogIndexRoute
  '/cn': typeof CnIndexRoute
  '/templates': typeof TemplatesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/google-one-tap': typeof ApiAuthGoogleOneTapRoute
  '/api/diag/email': typeof ApiDiagEmailRoute
  '/api/files/$': typeof ApiFilesSplatRoute
  '/api/generation-files/$': typeof ApiGenerationFilesSplatRoute
  '/api/referral/generate-code': typeof ApiReferralGenerateCodeRoute
  '/api/referral/stats': typeof ApiReferralStatsRoute
  '/api/stripe/checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe/portal': typeof ApiStripePortalRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/templates/$slug': typeof ApiTemplatesSlugRoute
  '/api/works/comment': typeof ApiWorksCommentRoute
  '/api/works/like': typeof ApiWorksLikeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_guest': typeof GuestRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/discover': typeof DiscoverRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_guest/forgot-password': typeof GuestForgotPasswordRoute
  '/_guest/login': typeof GuestLoginRoute
  '/_guest/reset-password': typeof GuestResetPasswordRoute
  '/_guest/signup': typeof GuestSignupRoute
  '/api/expand-vars': typeof ApiExpandVarsRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/generate-status': typeof ApiGenerateStatusRoute
  '/api/generations': typeof ApiGenerationsRoute
  '/api/grs-webhook': typeof ApiGrsWebhookRoute
  '/api/health': typeof ApiHealthRoute
  '/api/prompts': typeof ApiPromptsRoute
  '/api/share': typeof ApiShareRoute
  '/api/templates': typeof ApiTemplatesRouteWithChildren
  '/api/upload-url': typeof ApiUploadUrlRoute
  '/api/works': typeof ApiWorksRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/compare/ai-batch-generator-vs-single-prompt-tools': typeof CompareAiBatchGeneratorVsSinglePromptToolsRoute
  '/examples/$slug': typeof ExamplesSlugRoute
  '/g/$shareId': typeof GShareIdRoute
  '/my/generations': typeof MyGenerationsRoute
  '/my/prompts': typeof MyPromptsRoute
  '/my/works': typeof MyWorksRoute
  '/r/$code': typeof RCodeRoute
  '/templates/$slug': typeof TemplatesSlugRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/works/$workId': typeof WorksWorkIdRoute
  '/blog/': typeof BlogIndexRoute
  '/cn/': typeof CnIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/google-one-tap': typeof ApiAuthGoogleOneTapRoute
  '/api/diag/email': typeof ApiDiagEmailRoute
  '/api/files/$': typeof ApiFilesSplatRoute
  '/api/generation-files/$': typeof ApiGenerationFilesSplatRoute
  '/api/referral/generate-code': typeof ApiReferralGenerateCodeRoute
  '/api/referral/stats': typeof ApiReferralStatsRoute
  '/api/stripe/checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe/portal': typeof ApiStripePortalRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/templates/$slug': typeof ApiTemplatesSlugRoute
  '/api/works/comment': typeof ApiWorksCommentRoute
  '/api/works/like': typeof ApiWorksLikeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/discover'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/api/expand-vars'
    | '/api/generate'
    | '/api/generate-status'
    | '/api/generations'
    | '/api/grs-webhook'
    | '/api/health'
    | '/api/prompts'
    | '/api/share'
    | '/api/templates'
    | '/api/upload-url'
    | '/api/works'
    | '/blog/$slug'
    | '/compare/ai-batch-generator-vs-single-prompt-tools'
    | '/examples/$slug'
    | '/g/$shareId'
    | '/my/generations'
    | '/my/prompts'
    | '/my/works'
    | '/r/$code'
    | '/templates/$slug'
    | '/tools/$slug'
    | '/works/$workId'
    | '/blog/'
    | '/cn/'
    | '/templates/'
    | '/api/auth/$'
    | '/api/auth/google-one-tap'
    | '/api/diag/email'
    | '/api/files/$'
    | '/api/generation-files/$'
    | '/api/referral/generate-code'
    | '/api/referral/stats'
    | '/api/stripe/checkout'
    | '/api/stripe/portal'
    | '/api/stripe/webhook'
    | '/api/templates/$slug'
    | '/api/works/comment'
    | '/api/works/like'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/discover'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/api/expand-vars'
    | '/api/generate'
    | '/api/generate-status'
    | '/api/generations'
    | '/api/grs-webhook'
    | '/api/health'
    | '/api/prompts'
    | '/api/share'
    | '/api/templates'
    | '/api/upload-url'
    | '/api/works'
    | '/blog/$slug'
    | '/compare/ai-batch-generator-vs-single-prompt-tools'
    | '/examples/$slug'
    | '/g/$shareId'
    | '/my/generations'
    | '/my/prompts'
    | '/my/works'
    | '/r/$code'
    | '/templates/$slug'
    | '/tools/$slug'
    | '/works/$workId'
    | '/blog'
    | '/cn'
    | '/templates'
    | '/api/auth/$'
    | '/api/auth/google-one-tap'
    | '/api/diag/email'
    | '/api/files/$'
    | '/api/generation-files/$'
    | '/api/referral/generate-code'
    | '/api/referral/stats'
    | '/api/stripe/checkout'
    | '/api/stripe/portal'
    | '/api/stripe/webhook'
    | '/api/templates/$slug'
    | '/api/works/comment'
    | '/api/works/like'
  id:
    | '__root__'
    | '/'
    | '/_guest'
    | '/about'
    | '/discover'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/_guest/forgot-password'
    | '/_guest/login'
    | '/_guest/reset-password'
    | '/_guest/signup'
    | '/api/expand-vars'
    | '/api/generate'
    | '/api/generate-status'
    | '/api/generations'
    | '/api/grs-webhook'
    | '/api/health'
    | '/api/prompts'
    | '/api/share'
    | '/api/templates'
    | '/api/upload-url'
    | '/api/works'
    | '/blog/$slug'
    | '/compare/ai-batch-generator-vs-single-prompt-tools'
    | '/examples/$slug'
    | '/g/$shareId'
    | '/my/generations'
    | '/my/prompts'
    | '/my/works'
    | '/r/$code'
    | '/templates/$slug'
    | '/tools/$slug'
    | '/works/$workId'
    | '/blog/'
    | '/cn/'
    | '/templates/'
    | '/api/auth/$'
    | '/api/auth/google-one-tap'
    | '/api/diag/email'
    | '/api/files/$'
    | '/api/generation-files/$'
    | '/api/referral/generate-code'
    | '/api/referral/stats'
    | '/api/stripe/checkout'
    | '/api/stripe/portal'
    | '/api/stripe/webhook'
    | '/api/templates/$slug'
    | '/api/works/comment'
    | '/api/works/like'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  DiscoverRoute: typeof DiscoverRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiExpandVarsRoute: typeof ApiExpandVarsRoute
  ApiGenerateRoute: typeof ApiGenerateRoute
  ApiGenerateStatusRoute: typeof ApiGenerateStatusRoute
  ApiGenerationsRoute: typeof ApiGenerationsRoute
  ApiGrsWebhookRoute: typeof ApiGrsWebhookRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiPromptsRoute: typeof ApiPromptsRoute
  ApiShareRoute: typeof ApiShareRoute
  ApiTemplatesRoute: typeof ApiTemplatesRouteWithChildren
  ApiUploadUrlRoute: typeof ApiUploadUrlRoute
  ApiWorksRoute: typeof ApiWorksRouteWithChildren
  BlogSlugRoute: typeof BlogSlugRoute
  CompareAiBatchGeneratorVsSinglePromptToolsRoute: typeof CompareAiBatchGeneratorVsSinglePromptToolsRoute
  ExamplesSlugRoute: typeof ExamplesSlugRoute
  GShareIdRoute: typeof GShareIdRoute
  MyGenerationsRoute: typeof MyGenerationsRoute
  MyPromptsRoute: typeof MyPromptsRoute
  MyWorksRoute: typeof MyWorksRoute
  RCodeRoute: typeof RCodeRoute
  TemplatesSlugRoute: typeof TemplatesSlugRoute
  ToolsSlugRoute: typeof ToolsSlugRoute
  WorksWorkIdRoute: typeof WorksWorkIdRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CnIndexRoute: typeof CnIndexRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAuthGoogleOneTapRoute: typeof ApiAuthGoogleOneTapRoute
  ApiDiagEmailRoute: typeof ApiDiagEmailRoute
  ApiFilesSplatRoute: typeof ApiFilesSplatRoute
  ApiGenerationFilesSplatRoute: typeof ApiGenerationFilesSplatRoute
  ApiReferralGenerateCodeRoute: typeof ApiReferralGenerateCodeRoute
  ApiReferralStatsRoute: typeof ApiReferralStatsRoute
  ApiStripeCheckoutRoute: typeof ApiStripeCheckoutRoute
  ApiStripePortalRoute: typeof ApiStripePortalRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cn/': {
      id: '/cn/'
      path: '/cn'
      fullPath: '/cn/'
      preLoaderRoute: typeof CnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/works/$workId': {
      id: '/works/$workId'
      path: '/works/$workId'
      fullPath: '/works/$workId'
      preLoaderRoute: typeof WorksWorkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/$slug': {
      id: '/tools/$slug'
      path: '/tools/$slug'
      fullPath: '/tools/$slug'
      preLoaderRoute: typeof ToolsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$slug': {
      id: '/templates/$slug'
      path: '/templates/$slug'
      fullPath: '/templates/$slug'
      preLoaderRoute: typeof TemplatesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$code': {
      id: '/r/$code'
      path: '/r/$code'
      fullPath: '/r/$code'
      preLoaderRoute: typeof RCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/works': {
      id: '/my/works'
      path: '/my/works'
      fullPath: '/my/works'
      preLoaderRoute: typeof MyWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/prompts': {
      id: '/my/prompts'
      path: '/my/prompts'
      fullPath: '/my/prompts'
      preLoaderRoute: typeof MyPromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/generations': {
      id: '/my/generations'
      path: '/my/generations'
      fullPath: '/my/generations'
      preLoaderRoute: typeof MyGenerationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$shareId': {
      id: '/g/$shareId'
      path: '/g/$shareId'
      fullPath: '/g/$shareId'
      preLoaderRoute: typeof GShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/$slug': {
      id: '/examples/$slug'
      path: '/examples/$slug'
      fullPath: '/examples/$slug'
      preLoaderRoute: typeof ExamplesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/ai-batch-generator-vs-single-prompt-tools': {
      id: '/compare/ai-batch-generator-vs-single-prompt-tools'
      path: '/compare/ai-batch-generator-vs-single-prompt-tools'
      fullPath: '/compare/ai-batch-generator-vs-single-prompt-tools'
      preLoaderRoute: typeof CompareAiBatchGeneratorVsSinglePromptToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/works': {
      id: '/api/works'
      path: '/api/works'
      fullPath: '/api/works'
      preLoaderRoute: typeof ApiWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload-url': {
      id: '/api/upload-url'
      path: '/api/upload-url'
      fullPath: '/api/upload-url'
      preLoaderRoute: typeof ApiUploadUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/templates': {
      id: '/api/templates'
      path: '/api/templates'
      fullPath: '/api/templates'
      preLoaderRoute: typeof ApiTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/share': {
      id: '/api/share'
      path: '/api/share'
      fullPath: '/api/share'
      preLoaderRoute: typeof ApiShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/prompts': {
      id: '/api/prompts'
      path: '/api/prompts'
      fullPath: '/api/prompts'
      preLoaderRoute: typeof ApiPromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/grs-webhook': {
      id: '/api/grs-webhook'
      path: '/api/grs-webhook'
      fullPath: '/api/grs-webhook'
      preLoaderRoute: typeof ApiGrsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generations': {
      id: '/api/generations'
      path: '/api/generations'
      fullPath: '/api/generations'
      preLoaderRoute: typeof ApiGenerationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-status': {
      id: '/api/generate-status'
      path: '/api/generate-status'
      fullPath: '/api/generate-status'
      preLoaderRoute: typeof ApiGenerateStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate': {
      id: '/api/generate'
      path: '/api/generate'
      fullPath: '/api/generate'
      preLoaderRoute: typeof ApiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/expand-vars': {
      id: '/api/expand-vars'
      path: '/api/expand-vars'
      fullPath: '/api/expand-vars'
      preLoaderRoute: typeof ApiExpandVarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/signup': {
      id: '/_guest/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof GuestSignupRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/reset-password': {
      id: '/_guest/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof GuestResetPasswordRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/forgot-password': {
      id: '/_guest/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof GuestForgotPasswordRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/api/works/like': {
      id: '/api/works/like'
      path: '/like'
      fullPath: '/api/works/like'
      preLoaderRoute: typeof ApiWorksLikeRouteImport
      parentRoute: typeof ApiWorksRoute
    }
    '/api/works/comment': {
      id: '/api/works/comment'
      path: '/comment'
      fullPath: '/api/works/comment'
      preLoaderRoute: typeof ApiWorksCommentRouteImport
      parentRoute: typeof ApiWorksRoute
    }
    '/api/templates/$slug': {
      id: '/api/templates/$slug'
      path: '/$slug'
      fullPath: '/api/templates/$slug'
      preLoaderRoute: typeof ApiTemplatesSlugRouteImport
      parentRoute: typeof ApiTemplatesRoute
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/portal': {
      id: '/api/stripe/portal'
      path: '/api/stripe/portal'
      fullPath: '/api/stripe/portal'
      preLoaderRoute: typeof ApiStripePortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/checkout': {
      id: '/api/stripe/checkout'
      path: '/api/stripe/checkout'
      fullPath: '/api/stripe/checkout'
      preLoaderRoute: typeof ApiStripeCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/referral/stats': {
      id: '/api/referral/stats'
      path: '/api/referral/stats'
      fullPath: '/api/referral/stats'
      preLoaderRoute: typeof ApiReferralStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/referral/generate-code': {
      id: '/api/referral/generate-code'
      path: '/api/referral/generate-code'
      fullPath: '/api/referral/generate-code'
      preLoaderRoute: typeof ApiReferralGenerateCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generation-files/$': {
      id: '/api/generation-files/$'
      path: '/api/generation-files/$'
      fullPath: '/api/generation-files/$'
      preLoaderRoute: typeof ApiGenerationFilesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/$': {
      id: '/api/files/$'
      path: '/api/files/$'
      fullPath: '/api/files/$'
      preLoaderRoute: typeof ApiFilesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/diag/email': {
      id: '/api/diag/email'
      path: '/api/diag/email'
      fullPath: '/api/diag/email'
      preLoaderRoute: typeof ApiDiagEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google-one-tap': {
      id: '/api/auth/google-one-tap'
      path: '/api/auth/google-one-tap'
      fullPath: '/api/auth/google-one-tap'
      preLoaderRoute: typeof ApiAuthGoogleOneTapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GuestRouteRouteChildren {
  GuestForgotPasswordRoute: typeof GuestForgotPasswordRoute
  GuestLoginRoute: typeof GuestLoginRoute
  GuestResetPasswordRoute: typeof GuestResetPasswordRoute
  GuestSignupRoute: typeof GuestSignupRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestForgotPasswordRoute: GuestForgotPasswordRoute,
  GuestLoginRoute: GuestLoginRoute,
  GuestResetPasswordRoute: GuestResetPasswordRoute,
  GuestSignupRoute: GuestSignupRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

interface ApiTemplatesRouteChildren {
  ApiTemplatesSlugRoute: typeof ApiTemplatesSlugRoute
}

const ApiTemplatesRouteChildren: ApiTemplatesRouteChildren = {
  ApiTemplatesSlugRoute: ApiTemplatesSlugRoute,
}

const ApiTemplatesRouteWithChildren = ApiTemplatesRoute._addFileChildren(
  ApiTemplatesRouteChildren,
)

interface ApiWorksRouteChildren {
  ApiWorksCommentRoute: typeof ApiWorksCommentRoute
  ApiWorksLikeRoute: typeof ApiWorksLikeRoute
}

const ApiWorksRouteChildren: ApiWorksRouteChildren = {
  ApiWorksCommentRoute: ApiWorksCommentRoute,
  ApiWorksLikeRoute: ApiWorksLikeRoute,
}

const ApiWorksRouteWithChildren = ApiWorksRoute._addFileChildren(
  ApiWorksRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuestRouteRoute: GuestRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  DiscoverRoute: DiscoverRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiExpandVarsRoute: ApiExpandVarsRoute,
  ApiGenerateRoute: ApiGenerateRoute,
  ApiGenerateStatusRoute: ApiGenerateStatusRoute,
  ApiGenerationsRoute: ApiGenerationsRoute,
  ApiGrsWebhookRoute: ApiGrsWebhookRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiPromptsRoute: ApiPromptsRoute,
  ApiShareRoute: ApiShareRoute,
  ApiTemplatesRoute: ApiTemplatesRouteWithChildren,
  ApiUploadUrlRoute: ApiUploadUrlRoute,
  ApiWorksRoute: ApiWorksRouteWithChildren,
  BlogSlugRoute: BlogSlugRoute,
  CompareAiBatchGeneratorVsSinglePromptToolsRoute:
    CompareAiBatchGeneratorVsSinglePromptToolsRoute,
  ExamplesSlugRoute: ExamplesSlugRoute,
  GShareIdRoute: GShareIdRoute,
  MyGenerationsRoute: MyGenerationsRoute,
  MyPromptsRoute: MyPromptsRoute,
  MyWorksRoute: MyWorksRoute,
  RCodeRoute: RCodeRoute,
  TemplatesSlugRoute: TemplatesSlugRoute,
  ToolsSlugRoute: ToolsSlugRoute,
  WorksWorkIdRoute: WorksWorkIdRoute,
  BlogIndexRoute: BlogIndexRoute,
  CnIndexRoute: CnIndexRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAuthGoogleOneTapRoute: ApiAuthGoogleOneTapRoute,
  ApiDiagEmailRoute: ApiDiagEmailRoute,
  ApiFilesSplatRoute: ApiFilesSplatRoute,
  ApiGenerationFilesSplatRoute: ApiGenerationFilesSplatRoute,
  ApiReferralGenerateCodeRoute: ApiReferralGenerateCodeRoute,
  ApiReferralStatsRoute: ApiReferralStatsRoute,
  ApiStripeCheckoutRoute: ApiStripeCheckoutRoute,
  ApiStripePortalRoute: ApiStripePortalRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
