/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuestRouteRouteImport } from './routes/_guest/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CnIndexRouteImport } from './routes/cn/index'
import { Route as ApiUploadUrlRouteImport } from './routes/api/upload-url'
import { Route as ApiGenerateStatusRouteImport } from './routes/api/generate-status'
import { Route as ApiGenerateRouteImport } from './routes/api/generate'
import { Route as ApiDebugRouteImport } from './routes/api/debug'
import { Route as ApiAuthTestRouteImport } from './routes/api/auth-test'
import { Route as GuestSignupRouteImport } from './routes/_guest/signup'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as ApiFilesSplatRouteImport } from './routes/api/files/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const GuestRouteRoute = GuestRouteRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CnIndexRoute = CnIndexRouteImport.update({
  id: '/cn/',
  path: '/cn/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadUrlRoute = ApiUploadUrlRouteImport.update({
  id: '/api/upload-url',
  path: '/api/upload-url',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateStatusRoute = ApiGenerateStatusRouteImport.update({
  id: '/api/generate-status',
  path: '/api/generate-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateRoute = ApiGenerateRouteImport.update({
  id: '/api/generate',
  path: '/api/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugRoute = ApiDebugRouteImport.update({
  id: '/api/debug',
  path: '/api/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthTestRoute = ApiAuthTestRouteImport.update({
  id: '/api/auth-test',
  path: '/api/auth-test',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestSignupRoute = GuestSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRouteRoute,
} as any)
const ApiFilesSplatRoute = ApiFilesSplatRouteImport.update({
  id: '/api/files/$',
  path: '/api/files/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/api/auth-test': typeof ApiAuthTestRoute
  '/api/debug': typeof ApiDebugRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/generate-status': typeof ApiGenerateStatusRoute
  '/api/upload-url': typeof ApiUploadUrlRoute
  '/cn/': typeof CnIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/files/$': typeof ApiFilesSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/api/auth-test': typeof ApiAuthTestRoute
  '/api/debug': typeof ApiDebugRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/generate-status': typeof ApiGenerateStatusRoute
  '/api/upload-url': typeof ApiUploadUrlRoute
  '/cn': typeof CnIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/files/$': typeof ApiFilesSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_guest': typeof GuestRouteRouteWithChildren
  '/_guest/login': typeof GuestLoginRoute
  '/_guest/signup': typeof GuestSignupRoute
  '/api/auth-test': typeof ApiAuthTestRoute
  '/api/debug': typeof ApiDebugRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/generate-status': typeof ApiGenerateStatusRoute
  '/api/upload-url': typeof ApiUploadUrlRoute
  '/cn/': typeof CnIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/files/$': typeof ApiFilesSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/api/auth-test'
    | '/api/debug'
    | '/api/generate'
    | '/api/generate-status'
    | '/api/upload-url'
    | '/cn/'
    | '/api/auth/$'
    | '/api/files/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/api/auth-test'
    | '/api/debug'
    | '/api/generate'
    | '/api/generate-status'
    | '/api/upload-url'
    | '/cn'
    | '/api/auth/$'
    | '/api/files/$'
  id:
    | '__root__'
    | '/'
    | '/_guest'
    | '/_guest/login'
    | '/_guest/signup'
    | '/api/auth-test'
    | '/api/debug'
    | '/api/generate'
    | '/api/generate-status'
    | '/api/upload-url'
    | '/cn/'
    | '/api/auth/$'
    | '/api/files/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
  ApiAuthTestRoute: typeof ApiAuthTestRoute
  ApiDebugRoute: typeof ApiDebugRoute
  ApiGenerateRoute: typeof ApiGenerateRoute
  ApiGenerateStatusRoute: typeof ApiGenerateStatusRoute
  ApiUploadUrlRoute: typeof ApiUploadUrlRoute
  CnIndexRoute: typeof CnIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiFilesSplatRoute: typeof ApiFilesSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cn/': {
      id: '/cn/'
      path: '/cn'
      fullPath: '/cn/'
      preLoaderRoute: typeof CnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload-url': {
      id: '/api/upload-url'
      path: '/api/upload-url'
      fullPath: '/api/upload-url'
      preLoaderRoute: typeof ApiUploadUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-status': {
      id: '/api/generate-status'
      path: '/api/generate-status'
      fullPath: '/api/generate-status'
      preLoaderRoute: typeof ApiGenerateStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate': {
      id: '/api/generate'
      path: '/api/generate'
      fullPath: '/api/generate'
      preLoaderRoute: typeof ApiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug': {
      id: '/api/debug'
      path: '/api/debug'
      fullPath: '/api/debug'
      preLoaderRoute: typeof ApiDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth-test': {
      id: '/api/auth-test'
      path: '/api/auth-test'
      fullPath: '/api/auth-test'
      preLoaderRoute: typeof ApiAuthTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/signup': {
      id: '/_guest/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof GuestSignupRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/api/files/$': {
      id: '/api/files/$'
      path: '/api/files/$'
      fullPath: '/api/files/$'
      preLoaderRoute: typeof ApiFilesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GuestRouteRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
  GuestSignupRoute: typeof GuestSignupRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
  GuestSignupRoute: GuestSignupRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuestRouteRoute: GuestRouteRouteWithChildren,
  ApiAuthTestRoute: ApiAuthTestRoute,
  ApiDebugRoute: ApiDebugRoute,
  ApiGenerateRoute: ApiGenerateRoute,
  ApiGenerateStatusRoute: ApiGenerateStatusRoute,
  ApiUploadUrlRoute: ApiUploadUrlRoute,
  CnIndexRoute: CnIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiFilesSplatRoute: ApiFilesSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
