import { screen } from "@testing-library/react";
import { describe, it, expect } from "vitest";

import { renderWithProviders } from "#test/test-utils";

import { ResultCard } from "../ResultCard";
import type { GeneratedResult } from "../types";

const completeResult: GeneratedResult = {
  id: "result_1",
  combination: {
    variables: { var_0: "cat", var_1: "forest" },
    prompt: "A cat in a forest",
  },
  imageUrl: "https://example.com/image.png",
  textContent: null,
  watermark: false,
  status: "complete",
};

const errorResult: GeneratedResult = {
  id: "result_2",
  combination: {
    variables: { var_0: "dog" },
    prompt: "A dog on a beach",
  },
  imageUrl: null,
  textContent: null,
  watermark: false,
  status: "error",
};

const pendingResult: GeneratedResult = {
  id: "result_3",
  combination: {
    variables: { var_0: "bird" },
    prompt: "A bird in the sky",
  },
  imageUrl: null,
  textContent: null,
  watermark: false,
  status: "pending",
};

describe("ResultCard", () => {
  it("renders prompt text", () => {
    renderWithProviders(<ResultCard result={completeResult} />);
    expect(screen.getByText("A cat in a forest")).toBeInTheDocument();
  });

  it("renders variable values", () => {
    renderWithProviders(<ResultCard result={completeResult} />);
    expect(screen.getByText(/var_0: cat/)).toBeInTheDocument();
    expect(screen.getByText(/var_1: forest/)).toBeInTheDocument();
  });

  it("renders image when imageUrl is provided", () => {
    renderWithProviders(<ResultCard result={completeResult} />);
    const img = screen.getByAltText("A cat in a forest");
    expect(img).toBeInTheDocument();
    expect(img).toHaveAttribute("src", "https://example.com/image.png");
  });

  it("shows error state for error result", () => {
    renderWithProviders(<ResultCard result={errorResult} />);
    expect(screen.getByText("Failed")).toBeInTheDocument();
  });

  it("shows placeholder icon for pending result", () => {
    renderWithProviders(<ResultCard result={pendingResult} />);
    // ImageIcon renders an svg - we verify no image or error text
    expect(screen.queryByAltText(/bird/)).not.toBeInTheDocument();
    expect(screen.queryByText("Failed")).not.toBeInTheDocument();
  });

  it("renders without variables section when variables is empty", () => {
    const noVarsResult: GeneratedResult = {
      id: "result_4",
      combination: {
        variables: {},
        prompt: "A simple prompt",
      },
      imageUrl: null,
      textContent: null,
      watermark: false,
      status: "complete",
    };
    renderWithProviders(<ResultCard result={noVarsResult} />);
    expect(screen.getByText("A simple prompt")).toBeInTheDocument();
  });

  // --- AI API simulation: Replicate/GRS image URLs ---
  it("renders image from Replicate-like URL", () => {
    const replicateResult: GeneratedResult = {
      ...completeResult,
      imageUrl: "https://replicate.delivery/pbix/abc123/output-0.png",
    };
    renderWithProviders(<ResultCard result={replicateResult} />);
    const img = screen.getByAltText("A cat in a forest");
    expect(img).toBeInTheDocument();
    expect(img).toHaveAttribute("src", "https://replicate.delivery/pbix/abc123/output-0.png");
  });

  it("renders image from GRS-like CDN URL", () => {
    const grsResult: GeneratedResult = {
      ...completeResult,
      imageUrl: "https://grs-cdn.com/output/sunset-beach/image.png",
    };
    renderWithProviders(<ResultCard result={grsResult} />);
    const img = screen.getByAltText("A cat in a forest");
    expect(img).toBeInTheDocument();
    expect(img).toHaveAttribute("src", "https://grs-cdn.com/output/sunset-beach/image.png");
  });

  it("shows watermark for low-credit users", () => {
    renderWithProviders(<ResultCard result={completeResult} showWatermark />);
    expect(screen.getByText("Generated by BatchlyAI")).toBeInTheDocument();
  });

  it("does not show watermark by default", () => {
    renderWithProviders(<ResultCard result={completeResult} />);
    expect(screen.queryByText("Generated by BatchlyAI")).not.toBeInTheDocument();
  });

  it("renders generating spinner for in-progress result", () => {
    const generatingResult: GeneratedResult = {
      id: "result_gen",
      combination: { variables: { var_0: "x" }, prompt: "test" },
      imageUrl: null,
      textContent: null,
      watermark: false,
      status: "generating",
    };
    renderWithProviders(<ResultCard result={generatingResult} />);
    // Should show a spinner, not an error or placeholder
    expect(screen.queryByText("Failed")).not.toBeInTheDocument();
    const spinner = document.querySelector(".animate-spin");
    expect(spinner).not.toBeNull();
  });
});
