import { screen } from "@testing-library/react";
import { describe, it, expect } from "vitest";

import { renderWithProviders } from "#test/test-utils";

import { ResultCard } from "../ResultCard";
import type { GeneratedResult } from "../types";

const completeResult: GeneratedResult = {
  id: "result_1",
  combination: {
    variables: { var_0: "cat", var_1: "forest" },
    prompt: "A cat in a forest",
  },
  imageUrl: "https://example.com/image.png",
  textContent: null,
  watermark: false,
  status: "complete",
};

const errorResult: GeneratedResult = {
  id: "result_2",
  combination: {
    variables: { var_0: "dog" },
    prompt: "A dog on a beach",
  },
  imageUrl: null,
  textContent: null,
  watermark: false,
  status: "error",
};

const pendingResult: GeneratedResult = {
  id: "result_3",
  combination: {
    variables: { var_0: "bird" },
    prompt: "A bird in the sky",
  },
  imageUrl: null,
  textContent: null,
  watermark: false,
  status: "pending",
};

describe("ResultCard", () => {
  it("renders prompt text", () => {
    renderWithProviders(<ResultCard result={completeResult} />);
    expect(screen.getByText("A cat in a forest")).toBeInTheDocument();
  });

  it("renders variable values", () => {
    renderWithProviders(<ResultCard result={completeResult} />);
    expect(screen.getByText(/var_0: cat/)).toBeInTheDocument();
    expect(screen.getByText(/var_1: forest/)).toBeInTheDocument();
  });

  it("renders image when imageUrl is provided", () => {
    renderWithProviders(<ResultCard result={completeResult} />);
    const img = screen.getByAltText("A cat in a forest");
    expect(img).toBeInTheDocument();
    expect(img).toHaveAttribute("src", "https://example.com/image.png");
  });

  it("shows error state for error result", () => {
    renderWithProviders(<ResultCard result={errorResult} />);
    expect(screen.getByText("Failed")).toBeInTheDocument();
  });

  it("shows placeholder icon for pending result", () => {
    renderWithProviders(<ResultCard result={pendingResult} />);
    // ImageIcon renders an svg - we verify no image or error text
    expect(screen.queryByAltText(/bird/)).not.toBeInTheDocument();
    expect(screen.queryByText("Failed")).not.toBeInTheDocument();
  });

  it("renders without variables section when variables is empty", () => {
    const noVarsResult: GeneratedResult = {
      id: "result_4",
      combination: {
        variables: {},
        prompt: "A simple prompt",
      },
      imageUrl: null,
      textContent: null,
      watermark: false,
      status: "complete",
    };
    renderWithProviders(<ResultCard result={noVarsResult} />);
    expect(screen.getByText("A simple prompt")).toBeInTheDocument();
  });

  // --- AI API simulation: Replicate/GRS image URLs ---
  it("renders image from Replicate-like URL", () => {
    const replicateResult: GeneratedResult = {
      ...completeResult,
      imageUrl: "https://replicate.delivery/pbix/abc123/output-0.png",
    };
    renderWithProviders(<ResultCard result={replicateResult} />);
    const img = screen.getByAltText("A cat in a forest");
    expect(img).toBeInTheDocument();
    expect(img).toHaveAttribute("src", "https://replicate.delivery/pbix/abc123/output-0.png");
  });

  it("renders image from GRS-like CDN URL", () => {
    const grsResult: GeneratedResult = {
      ...completeResult,
      imageUrl: "https://grs-cdn.com/output/sunset-beach/image.png",
    };
    renderWithProviders(<ResultCard result={grsResult} />);
    const img = screen.getByAltText("A cat in a forest");
    expect(img).toBeInTheDocument();
    expect(img).toHaveAttribute("src", "https://grs-cdn.com/output/sunset-beach/image.png");
  });

  it("shows watermark for low-credit users", () => {
    renderWithProviders(<ResultCard result={completeResult} showWatermark />);
    expect(screen.getByText("Generated by BatchlyAI")).toBeInTheDocument();
  });

  it("does not show watermark by default", () => {
    renderWithProviders(<ResultCard result={completeResult} />);
    expect(screen.queryByText("Generated by BatchlyAI")).not.toBeInTheDocument();
  });

  it("renders generating spinner for in-progress result", () => {
    const generatingResult: GeneratedResult = {
      id: "result_gen",
      combination: { variables: { var_0: "x" }, prompt: "test" },
      imageUrl: null,
      textContent: null,
      watermark: false,
      status: "generating",
    };
    renderWithProviders(<ResultCard result={generatingResult} />);
    expect(screen.queryByText("Failed")).not.toBeInTheDocument();
    const spinner = document.querySelector(".animate-spin");
    expect(spinner).not.toBeNull();
  });

  // --- Text content rendering ---
  it("renders text content for text generation results", () => {
    const textResult: GeneratedResult = {
      id: "result_text",
      combination: { variables: {}, prompt: "Say hello" },
      imageUrl: null,
      textContent: "Hello, world!",
      watermark: false,
      status: "complete",
    };
    renderWithProviders(<ResultCard result={textResult} />);
    expect(screen.getByText("Hello, world!")).toBeInTheDocument();
  });

  it("renders markdown bold in text content", () => {
    const textResult: GeneratedResult = {
      id: "result_md",
      combination: { variables: {}, prompt: "test" },
      imageUrl: null,
      textContent: "This is **bold** text",
      watermark: false,
      status: "complete",
    };
    renderWithProviders(<ResultCard result={textResult} />);
    const strong = document.querySelector("strong");
    expect(strong).not.toBeNull();
    expect(strong?.textContent).toBe("bold");
  });

  it("renders markdown italic in text content", () => {
    const textResult: GeneratedResult = {
      id: "result_md2",
      combination: { variables: {}, prompt: "test" },
      imageUrl: null,
      textContent: "This is *italic* text",
      watermark: false,
      status: "complete",
    };
    renderWithProviders(<ResultCard result={textResult} />);
    const em = document.querySelector("em");
    expect(em).not.toBeNull();
    expect(em?.textContent).toBe("italic");
  });

  it("renders markdown code in text content", () => {
    const textResult: GeneratedResult = {
      id: "result_md3",
      combination: { variables: {}, prompt: "test" },
      imageUrl: null,
      textContent: "Use `code` here",
      watermark: false,
      status: "complete",
    };
    renderWithProviders(<ResultCard result={textResult} />);
    const code = document.querySelector("code");
    expect(code).not.toBeNull();
    expect(code?.textContent).toBe("code");
  });

  // --- Download button ---
  it("shows download button for complete image result", () => {
    renderWithProviders(<ResultCard result={completeResult} />);
    const btn = document.querySelector("button[title='Download']");
    expect(btn).not.toBeNull();
  });

  it("shows download button for complete text result", () => {
    const textResult: GeneratedResult = {
      id: "result_text2",
      combination: { variables: {}, prompt: "test" },
      imageUrl: null,
      textContent: "Hello",
      watermark: false,
      status: "complete",
    };
    renderWithProviders(<ResultCard result={textResult} />);
    const btn = document.querySelector("button[title='Download']");
    expect(btn).not.toBeNull();
  });

  it("does not show download button for error result", () => {
    renderWithProviders(<ResultCard result={errorResult} />);
    const btn = document.querySelector("button[title='Download']");
    expect(btn).toBeNull();
  });

  it("shows watermark download hint for watermarked results", () => {
    renderWithProviders(<ResultCard result={completeResult} showWatermark />);
    const btn = document.querySelector("button[title='Download with watermark']");
    expect(btn).not.toBeNull();
  });

  // --- Mobile download button ---
  it("download button is always visible on mobile (opacity-100)", () => {
    renderWithProviders(<ResultCard result={completeResult} />);
    const btn = document.querySelector("button[title='Download']");
    expect(btn).not.toBeNull();
    expect(btn!.className).toContain("opacity-100");
    expect(btn!.className).toContain("md:opacity-0");
    expect(btn!.className).toContain("md:group-hover:opacity-100");
  });
});
